[package]
name = "algorithms"
version = "0.1.0"
authors = ["crypto-universe <ykp@protonmail.ch>"]
readme = "README.md"
keywords = ["algorithms"]
license = "MIT"
repository = "https://github.com/crypto-universe/algorithms"
description = "Just some algorithms"

[dependencies]
